[project]
name = "pyroquad"
version = "0.1.0"
description = "The Pyroquad game engine."
readme = "README.md"
requires-python = ">=3.10"

[tool.maturin]
include = ["pyroquad.pyi"]
abi3 = true

[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin.build"